// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJmUBfZHDx5UeFxXmjAlmss60bZL90rzY',
    appId: '1:125073612234:android:fcacfd503ccbe1848e8333',
    messagingSenderId: '125073612234',
    projectId: 'mile-rms',
    storageBucket: 'mile-rms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeUvq58991-7fGN_50w2EmfSmvR1EbTxY',
    appId: '1:125073612234:ios:966c0620be4c88908e8333',
    messagingSenderId: '125073612234',
    projectId: 'mile-rms',
    storageBucket: 'mile-rms.appspot.com',
    iosClientId: '125073612234-kg4kfme0lqttiipc3h3bg7l5rrm7sjqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeUvq58991-7fGN_50w2EmfSmvR1EbTxY',
    appId: '1:125073612234:ios:966c0620be4c88908e8333',
    messagingSenderId: '125073612234',
    projectId: 'mile-rms',
    storageBucket: 'mile-rms.appspot.com',
    iosClientId: '125073612234-kg4kfme0lqttiipc3h3bg7l5rrm7sjqd.apps.googleusercontent.com',
    iosBundleId: 'com.example.storeManagement',
  );

}
